const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const { execFileSync } = require("node:child_process");

const ROOT = path.resolve(__dirname, "..");

test("CI and release workflows exist and parse as YAML-ish", () => {
  const ci = path.join(ROOT, ".github/workflows/ci.yml");
  const rel = path.join(ROOT, ".github/workflows/release.yml");
  assert.ok(fs.existsSync(ci), "ci.yml must exist");
  assert.ok(fs.existsSync(rel), "release.yml must exist");
  for (const file of [ci, rel]) {
    const text = fs.readFileSync(file, "utf8");
    // Smoke check: must declare a top-level `name:`, `on:`, and `jobs:` block.
    assert.match(text, /^name:\s+\S+/m, `${path.basename(file)} missing name`);
    assert.match(text, /^on:\s*$|^on:\s*\S/m, `${path.basename(file)} missing on:`);
    assert.match(text, /^jobs:\s*$/m, `${path.basename(file)} missing jobs:`);
  }
});

test("release workflow only triggers on semver-shaped tags", () => {
  const text = fs.readFileSync(path.join(ROOT, ".github/workflows/release.yml"), "utf8");
  // Guard against accidentally widening the trigger to any tag.
  assert.match(text, /tags:\s*\n\s+- "v\[0-9\]\+\.\[0-9\]\+\.\[0-9\]\+"/);
});

test("LICENSE and CHANGELOG exist", () => {
  assert.ok(fs.existsSync(path.join(ROOT, "LICENSE")), "LICENSE missing");
  assert.ok(fs.existsSync(path.join(ROOT, "CHANGELOG.md")), "CHANGELOG missing");
});

test("updates.json is shape-correct and within one version of manifest", () => {
  const updates = JSON.parse(fs.readFileSync(path.join(ROOT, "updates.json"), "utf8"));
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, "src/manifest.json"), "utf8"));
  const id = manifest.applications?.zotero?.id;
  assert.ok(id, "manifest is missing addon id");
  const entry = updates.addons?.[id];
  assert.ok(entry, `updates.json has no entry for ${id}`);
  assert.ok(Array.isArray(entry.updates) && entry.updates.length > 0, "updates list is empty");
  const latest = entry.updates[entry.updates.length - 1];

  // updates.json is regenerated by the release workflow after a tag is
  // pushed, so during the bump-commit-tag interval it is allowed to lag
  // by exactly one version. Anything else is a real desync.
  const mv = manifest.version.split(".").map(Number);
  const lv = latest.version.split(".").map(Number);
  const isSame = mv.every((n, i) => n === lv[i]);
  const isOneBehind =
    (mv[0] === lv[0] && mv[1] === lv[1] && mv[2] === lv[2] + 1) ||
    (mv[0] === lv[0] && mv[1] === lv[1] + 1 && mv[2] === 0) ||
    (mv[0] === lv[0] + 1 && mv[1] === 0 && mv[2] === 0);
  assert.ok(
    isSame || isOneBehind,
    `updates.json latest (${latest.version}) must equal or be exactly one ` +
      `version behind manifest (${manifest.version}). The release workflow ` +
      `closes the gap on tag push.`
  );

  assert.match(latest.update_link, /^https:\/\//, "update_link must be https");
  assert.match(latest.update_hash, /^sha256:[a-f0-9]{64}$/i, "update_hash must be sha256:<64 hex>");
});

test("update-manifest.mjs rejects bad input", () => {
  const script = path.join(ROOT, "scripts/update-manifest.mjs");
  for (const args of [
    ["--version", "1.2", "--xpi-url", "https://x/y", "--sha256", "a".repeat(64)],
    ["--version", "1.2.3", "--xpi-url", "http://x/y", "--sha256", "a".repeat(64)],
    ["--version", "1.2.3", "--xpi-url", "https://x/y", "--sha256", "tooshort"]
  ]) {
    assert.throws(
      () => {
        execFileSync(process.execPath, [script, ...args], { stdio: "pipe" });
      },
      undefined,
      `expected rejection for args: ${args.join(" ")}`
    );
  }
});

test("bump-version.sh is executable and refuses non-monotonic targets", () => {
  const script = path.join(ROOT, "scripts/bump-version.sh");
  const stat = fs.statSync(script);
  // 0o111 (--x--x--x) — at least the owner can execute.
  assert.ok((stat.mode & 0o100) !== 0, "bump-version.sh must be executable");

  const pkgVersion = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")).version;
  // 0.0.0 must be lower than current.
  assert.throws(
    () => {
      execFileSync(script, ["0.0.0"], { stdio: "pipe", cwd: ROOT });
    },
    undefined,
    `expected refusal to downgrade to 0.0.0 from ${pkgVersion}`
  );
});

test("actions are pinned to full lowercase SHAs with version comments", () => {
  const workflows = [".github/workflows/ci.yml", ".github/workflows/release.yml"];
  const expected = new Map([
    ["actions/checkout", "d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0"],
    ["actions/setup-node", "249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0"],
    ["actions/upload-artifact", "043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1"],
    ["softprops/action-gh-release", "3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2"]
  ]);
  const references = [];

  for (const workflow of workflows) {
    const text = fs.readFileSync(path.join(ROOT, workflow), "utf8");
    for (const line of text.split("\n")) {
      if (!/\buses:\s*/.test(line)) continue;
      const match = line.match(/^\s+uses:\s+([^\s]+)(?:\s+#\s+(.+?))?\s*$/);
      assert.ok(match, `${workflow} has an invalid uses line: ${line}`);
      const [owner, action] = match[1].split("@");
      assert.match(owner, /^[\w.-]+\/[\w.-]+$/, `${workflow} has an invalid action name`);
      assert.match(action, /^[0-9a-f]{40}$/, `${workflow} has a floating or malformed action ref`);
      assert.match(
        match[2] ?? "",
        /^v\d+\.\d+\.\d+$/,
        `${workflow} action ref is missing a version comment`
      );
      references.push(`${owner}@${action} # ${match[2]}`);
    }
  }

  assert.ok(references.length > 0, "expected at least one external action reference");
  for (const reference of references) {
    const [owner] = reference.split("@");
    assert.equal(reference, `${owner}@${expected.get(owner)}`, `unexpected pin for ${owner}`);
  }
  assert.deepEqual(
    new Set(references.map((reference) => reference.split("@")[0])),
    new Set(expected.keys())
  );
});

test("Dependabot has weekly actions and npm update entries", () => {
  const configPath = path.join(ROOT, ".github/dependabot.yml");
  assert.ok(fs.existsSync(configPath), "Dependabot configuration is missing");
  const text = fs.readFileSync(configPath, "utf8");
  for (const ecosystem of ["github-actions", "npm"]) {
    assert.match(
      text,
      new RegExp(
        `- package-ecosystem:\\s+${ecosystem}\\n\\s+directory:\\s+\\/\\n\\s+schedule:\\n\\s+interval:\\s+weekly`
      ),
      `Dependabot must check ${ecosystem} weekly from /`
    );
  }
});
